### ISSUE TITLE
Example usage with swc plugins

### ISSUE THREAD

**Issue by kylemh** [Karibash/storybook-addon-swc#21]
I'd like to use SWC with the [official styled-components plug-in](https://github.com/swc-project/plugins/tree/main/packages/styled-components) in Storybook.

How might I do this?

**Comment by Karibash** [comment]
@kylemh 
It should be possible to use plug-ins in SWC by writing the following configuration file.
However, as for the [styled-components plugin](https://github.com/swc-project/plugins/tree/main/packages/styled-components), it seems that it has not been released to npm yet because package.json is not prepared.
I think you need to clone the repository and place it directly in your project or wait until it is released.

```js
module.exports = {
  addons: [
    {
      name: 'storybook-addon-swc',
      options: {
        swcLoaderOptions: {
          jsc: {
            experimental: {
              plugins: [['plugin-name', {}]],
            },
          },
        },
      },
    },
  ],
};
```

reference: https://github.com/swc-project/swc/blob/c5a0c9a0ab2345aa9c41a40100d049a144dfb70f/node-swc/src/types.ts#L511

**Comment by Karibash** [comment]
Added documentation about the swc plugins to README.md.
https://github.com/Karibash/storybook-addon-swc#swc-plugins

**Comment by kylemh** [comment]
Thanks a ton, @Karibash for both resolutions
